In [1]:
import numpy as np
%matplotlib inline
from scipy.io import loadmat
import time

In [2]:
"""
edgelist format for MultiVERSE:
(layer, source, target, weight)
"""

def edgelist_A(layer):
    edges = np.transpose(np.nonzero(layer))
    ones = np.ones((edges.shape[0],1)).astype(int)
    new_edges = np.hstack((ones, edges, ones))
    return new_edges


def edgelist_B(layer):
    
    mean = np.mean(layer)
    std = np.std(layer)
    threshold = mean + 3*std
    if threshold > 1:
        threshold = .99
    above_threshold = layer > threshold
    
    edges = np.transpose(np.where(above_threshold)).astype(int)
    ones = np.ones((edges.shape[0],1)).astype(int)
    twos = ones * 2
    new_edges = np.hstack((twos, edges, ones))
    return new_edges

In [3]:
aminer = loadmat('AminerData_v6.mat')
A1 = aminer['G'][0,0][0][0][0]
A2 = aminer['G'][0,1][0][0][0]
A3 = aminer['G'][0,2][0][0][0]

In [2]:
aminer = loadmat('AminerData_v6.mat')
A3 = aminer['G'][0,2][0][0][0]

In [4]:
A1.shape, A2.shape, A3.shape

((62602, 62602), (899, 899), (61843, 61843))

In [5]:
A1_edges = edgelist_A(A1)
A1_edges

array([[    1,     6, 16609,     1],
       [    1,     6, 29395,     1],
       [    1,     6, 35280,     1],
       ...,
       [    1, 55757, 23829,     1],
       [    1, 55763, 53004,     1],
       [    1, 55769, 32223,     1]])

In [6]:
A2_edges = edgelist_A(A2)
A2_edges

array([[  1,   1,  22,   1],
       [  1,   1,  29,   1],
       [  1,   1,  48,   1],
       ...,
       [  1, 742, 587,   1],
       [  1, 742, 631,   1],
       [  1, 742, 718,   1]])

In [7]:
A3_edges = edgelist_A(A3)
A3_edges

array([[    1,     0,    26,     1],
       [    1,     0,    37,     1],
       [    1,     0,    50,     1],
       ...,
       [    1, 61840, 26065,     1],
       [    1, 61840, 61839,     1],
       [    1, 61842, 14173,     1]])

In [6]:
A3_edges.shape

(402074, 4)

In [ ]:
B1 = np.load('cosine_matrices/B1.npz')
B1 = B1['B1']
B1.shape

In [14]:
B2 = np.load('B2.npz') 
B2 = B2['B2']
B2.shape

(899, 899)

In [7]:
B3 = np.load('B3.npz') 
B3 = B3['B3']
B3.shape

(61843, 61843)

In [19]:
tic = time.time()
B1_edges = edgelist_B(B1)
toc = time.time()
print(toc-tic)

B1_edges

44.35867476463318


array([[    2,     0,     0,     1],
       [    2,     0,  2126,     1],
       [    2,     0,  6470,     1],
       ...,
       [    2, 62601, 62594,     1],
       [    2, 62601, 62600,     1],
       [    2, 62601, 62601,     1]])

In [15]:
B2_edges = edgelist_B(B2)
B2_edges

array([[  2,   1,   1,   1],
       [  2,   1, 298,   1],
       [  2,   1, 450,   1],
       ...,
       [  2, 898, 445,   1],
       [  2, 898, 889,   1],
       [  2, 898, 898,   1]])

In [13]:
B3_edges = edgelist_B(B3)
B3_edges

array([[    2,     0,     0,     1],
       [    2,     0,    37,     1],
       [    2,     0,   701,     1],
       ...,
       [    2, 61840, 61840,     1],
       [    2, 61842,  6072,     1],
       [    2, 61842, 61842,     1]])

In [20]:
layer1_multiplex_edges = np.vstack((A1_edges, B1_edges))
layer1_multiplex_edges.shape

(96624676, 4)

In [16]:
layer2_multiplex_edges = np.vstack((A2_edges, B2_edges))
layer2_multiplex_edges.shape

(20542, 4)

In [14]:
layer3_multiplex_edges = np.vstack((A3_edges, B3_edges))
layer3_multiplex_edges.shape

(138328099, 4)

In [24]:
layer1_multiplex_edges

array([[    1,     6, 16609,     1],
       [    1,     6, 29395,     1],
       [    1,     6, 35280,     1],
       ...,
       [    2, 62601, 62594,     1],
       [    2, 62601, 62600,     1],
       [    2, 62601, 62601,     1]])

In [17]:
layer2_multiplex_edges

array([[  1,   1,  22,   1],
       [  1,   1,  29,   1],
       [  1,   1,  48,   1],
       ...,
       [  2, 898, 445,   1],
       [  2, 898, 889,   1],
       [  2, 898, 898,   1]])

In [15]:
layer3_multiplex_edges

array([[    1,     0,    26,     1],
       [    1,     0,    37,     1],
       [    1,     0,    50,     1],
       ...,
       [    2, 61840, 61840,     1],
       [    2, 61842,  6072,     1],
       [    2, 61842, 61842,     1]])

In [25]:
np.savetxt('edges/Aminer_layer1_multiplex_edges.txt', layer1_multiplex_edges, fmt='%d', delimiter=' ')  # save as input .txt file for MultiVERSE

In [18]:
np.savetxt('edges/Aminer_layer2_multiplex_edges.txt', layer2_multiplex_edges, fmt='%d', delimiter=' ')  # save as input .txt file for MultiVERSE

In [16]:
np.savetxt('edges/Aminer_layer3_multiplex_edges.txt', layer3_multiplex_edges, fmt='%d', delimiter=' ')  # save as input .txt file for MultiVERSE